name: build
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: postgresql
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - uses: ./.github/actions/database-support
      - name: migrate test database
        run: |
          psql --host localhost --username postgresql < databases/create_databases.sql
          /usr/local/bin/flyway -user=initialdev -password=initialdev -url="jdbc:postgresql://localhost/sandals_test" -locations=filesystem:databases/spring migrate
        env:
          PGPASSWORD: postgresql
      - name: "build"
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: spring-server.jar
          path: services/spring-server/build/libs/spring-server.jar
          retention-days: 1

  build-the-artifact:
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: spring-server.jar
          path: services/spring-server/build/libs
      - name: "pack"
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/embedded-server-review/embedded-server:${{ github.sha }} . \
            --platform linux/amd64